### PR TITLE
Fix NPQ service fee rounding with addition to first payment

### LINKED ISSUE #34: NPQ service fee totals don't add up due to rounding
Total of service schedule doesn't add up to service fee total.

Demonstration and possible  https://github.com/DFE-Digital/cpd-payment-calculations/commit/b6b05d6c211824e2e56015fca3339acf9efa317d

[CPDTP-106](https://dfedigital.atlassian.net/browse/CPDTP-106)

### PR DESCRIPTION
**Pull request by timabell**
A piece of [CPDTP-106](https://dfedigital.atlassian.net/browse/CPDTP-106)

This may not be the final approach, but it gets the numbers to add up and we can iterate on this later.

Fixes #34

### CODE REVIEW

**Review by plisovin — APPROVED** [review]

File: lib/services/npq/service_fees.rb [hunk 1]
```diff
@@ -23,7 +24,9 @@ def monthly_service_fee
       end
 
       def service_fee_payment_schedule
-        [monthly_service_fee] * number_of_service_fee_payments
+        schedule = [monthly_service_fee] * number_of_service_fee_payments
+        schedule[0] += total_service_fee - schedule.sum
+        schedule
```
Comment (blackrat) [inline lib/services/npq/service_fees.rb:29]:
```suggestion
        ([monthly_service_fee] * number_of_service_fee_payments).tap do |schedule|
          schedule[0] += total_service_fee - schedule.sum
        end
```

File: spec/features/npq/npq_payment_calculation.feature [hunk 2]
```diff
@@ -87,7 +89,7 @@ Feature: NPQ single-qualification payment schedule calculation
     Then expected variable payments should be as above
       And the service fee payment schedule should be:
         | Month | Service Fee |
-        | 1     | £25,612.90  |
+        | 1     | £25,613.00  |
```
Comment (blackrat) [inline spec/features/npq/npq_payment_calculation.feature:92]: Should we have an example that rounds up incorrectly and requires a deduction from the first Service Fee?

**Review by blackrat — CHANGES_REQUESTED** [review]

**Review by blackrat — APPROVED** [review]
